### ISSUE TITLE
Add GPG commit signing installation

### ISSUE THREAD

**Issue by kn0wl3dge** [0pendev/dotfiles#8]
Hi,

It could be interesting to add the followings actions to the setup script:
- install pinentry program
- update gpg-agent configuration
- retrieve the public key from github
- trust the key
- configure git commit signing

**Comment by 0pendev** [comment]
> Hi,
> 
> It could be interesting to add the followings actions to the setup script:
> 
>     * install pinentry program
I'll see if I really need to add one but I might add pinentry as it does not add new dependencies
> 
>     * update gpg-agent configuration
For now it is working just fine. What could be updated ?
>     * retrieve the public key from github
For now I will not add it in my install script
>     * trust the key
same
>     * configure git commit signing
already in my .gitconfig
